name: Terragrunt Dev Plan

on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  terragrunt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (Service Principal Secret)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Install Terragrunt
        run: |
          TG_VERSION=0.96.1
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VERSION}/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Terragrunt init
        working-directory: dev
        env:
          CLIENT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
          CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          TENANT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}
          SUBSCRIPTION_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}
        run: terragrunt run -all init  
        
      - name: Terragrunt Run-All Plan
        working-directory: dev
        env:
          CLIENT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
          CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          TENANT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}
          SUBSCRIPTION_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}
        run: terragrunt run -all plan
        
